### ISSUE TITLE
Name clash with the SELinux policy for Pulp2

### ISSUE THREAD

**Issue by evgeni** [pulp/pulp-selinux#4]
This repo is called `pulp-selinux`, but it really contains the policy for Pulp3 aka pulpcore, so I personally would have expected it to be called `pulpcore-selinux`.

Additionally, there is a `pulp-selinux` RPM package, built from the pulp2 source, so we'll have to rename this during packaging anyways as otherwise we end up with two packages with the same name.

**Comment by bmbouter** [comment]
Closing since it was moved to pulp.plan.io here: https://pulp.plan.io/issues/5994
