### ISSUE TITLE
filecontext conflict with pulp2

### ISSUE THREAD

**Issue by evgeni** [pulp/pulp-selinux#5]
`pulp.fc` currently defines
```
/var/lib/pulp(/.*)? 	gen_context(system_u:object_r:pulpcore_var_lib_t,s0)
```

However, [pulp-server.fc](https://github.com/pulp/pulp/blob/2-master/server/selinux/server/pulp-server.fc#L6) from pulp2 defines this as:
```
/var/lib/pulp(/.*)? gen_context(system_u:object_r:httpd_sys_rw_content_t,s0)
```

I'd expect this makes these two policies not co-installable.

**Comment by bmbouter** [comment]
Closing since it was moved to pulp.plan.io here https://pulp.plan.io/issues/5995
